SCR_EditorManagerCore {
 m_ModePrefabs {
  SCR_EditorModePrefab "{60967E00515335CD}" {
   m_Mode COE_COMMANDER
   m_Prefab "{4A99F32BDA6CF38B}Prefabs/Editor/Modes/COE_EditorModeCommander.et"
   m_Flags 36
   m_ModeUIInfo SCR_EditorModeUIInfo {
    Name "#COE-Editor_CommanderMode_Name"
    m_ModeColor 0.2 0.4 0.8 1
    m_iOrder 100
   }
  }
 }
}