StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{609A2A3C9AC2C20F}" {
   Id "COE-Action_Briefing"
   Target_en_us "Enter briefing"
   Target_ko_kr "브리핑 참가"
   Modified 1620744497
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609A2A3C8BABD4C6}" {
   Id "COE-Action_CancelAO"
   Target_en_us "Cancel all AOs"
   Target_ko_kr "모든 작전구역 취소"
   Modified 1727862254
   Author "kex"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6A042B69EB2191AD}" {
   Id "COE-Action_DismissAllAI"
   Target_en_us "Dismiss all"
   Target_ko_kr "모두 해산"
   Modified 1778659420
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{6099212B7E1B92EE}" {
   Id "COE-Action_GenerateAO"
   Target_en_us "Generate AOs and tasks"
   Target_ko_kr "작전구역 및 임무 생성"
   Modified 1727862294
   Author "kex"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6098EB566634958C}" {
   Id "COE-Action_ObjectiveAttributes"
   Target_en_us "Open objective properties"
   Target_ko_kr "목표 속성 열기"
   Modified 1620743183
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB56B679A6E9}" {
   Id "COE-Action_SelectAO"
   Target_en_us "Select AOs and tasks"
   Target_ko_kr "작전구역 및 임무 선택"
   Modified 1727862300
   Author "kex"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{66FB2482928FE156}" {
   Id "COE-Action_SetExfilPoint"
   Target_en_us "Set exfil point"
   Target_ko_kr "탈출 지점 설정"
   Modified 1727861882
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{609F29E3E0663A77}" {
   Id "COE-Action_SetInsertionPoint"
   Target_en_us "Set insertion point"
   Target_ko_kr "투입 지점 설정"
   Modified 1621047339
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{60A0A47D302DACF1}" {
   Id "COE-ActionCategory_CombatOpsCommands"
   Target_en_us "Combat Ops Commands"
   Target_ko_kr "Combat Ops 명령"
   Modified 1621412051
   Author "kex"
   LastChanged "swellig"
  }
  CustomStringTableItem "{6172533A32929855}" {
   Id "COE-Briefing_Description"
   Target_en_us "Co-operative infantry gameplay with dynamic objectives for Arma Reforger. Next generation of Combat Ops Enhanced with inspiration from mbrdmn's Dynamic Recon Ops from Arma 3."\
   Target_ko_kr "동적으로 생성되는 목표와 함께하는 Arma Reforger 협동 보병 게임플레이입니다. Combat Ops Enhanced의 차세대 버전이며, Arma 3의 mbrdmn's Dynamic Recon Ops에서 영감을 받았습니다."
   ""
   Modified 1634888121
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{6155376789FAB1FC}" {
   Id "COE-DeployScreen_NoFactionsAvailable"
   Target_en_us "There are no available factions. Please vote for a commander or wait for them to set a faction."
   Target_ko_kr "참여 가능한 세력이 없습니다. 지휘관을 투표로 선출하거나 지휘관이 세력을 설정할 때까지 기다리세요."
   Modified 1632978970
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB52AA9BEC47}" {
   Id "COE-Dialog_SelectAO_Location"
   Target_en_us "Location:"
   Target_ko_kr "장소:"
   Modified 1620743035
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{61585B1D0CD2464E}" {
   Id "COE-Editor_AORadius_Attribute_Description"
   Target_en_us "Set radius of the AO"
   Target_ko_kr "작전구역의 반경을 설정합니다"
   Modified 1633217948
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{61585B1D03EC739D}" {
   Id "COE-Editor_AORadius_Attribute_Name"
   Target_en_us "AO radius"
   Target_ko_kr "작전구역 반경"
   Modified 1633217920
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609C43226A8405AB}" {
   Id "COE-Editor_AttributeCategory_CombatOps_Name"
   Target_en_us "Combat Ops"
   Target_ko_kr "Combat Ops"
   Modified 1620867316
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6594C0799DBF5B9D}" {
   Id "COE-Editor_CivilianFaction_Attribute_Description"
   Target_en_us "Set faction for civilian AI"
   Target_ko_kr "민간인 AI의 세력을 설정합니다"
   Modified 1704248386
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6594C0799BF012BF}" {
   Id "COE-Editor_CivilianFaction_Attribute_Name"
   Target_en_us "Civilian faction"
   Target_ko_kr "민간인 세력"
   Modified 1704248370
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{630708E9CB6A6A2D}" {
   Id "COE-Editor_CiviliansEnabled_Attribute_Description"
   Target_en_us "Set whether civilians should be spawned"
   Target_ko_kr "민간인을 생성할지 설정합니다"
   Modified 1661407709
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{630708E9D59FD9AC}" {
   Id "COE-Editor_CiviliansEnabled_Attribute_Name"
   Target_en_us "Spawn civilians"
   Target_ko_kr "민간인 생성"
   Modified 1661407688
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6098EB54F6C1E4B8}" {
   Id "COE-Editor_CommanderMode_Name"
   Target_en_us "Commander"
   Target_ko_kr "지휘관"
   Modified 1620644120
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609C9CFFC2CE19E5}" {
   Id "COE-Editor_EnemyAICountMultiplier_Attribute_Description"
   Target_en_us "Total enemy AI count for an AO will be this multiplier times the total player count (ignored when below minimum count)"
   Target_ko_kr "작전구역의 전체 적 AI 수는 전체 플레이어 수에 이 배율을 곱한 값이 됩니다 (최소 수보다 적으면 무시됨)"
   Modified 1620882763
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609C9CFFC6C3DF41}" {
   Id "COE-Editor_EnemyAICountMultiplier_Attribute_Name"
   Target_en_us "Enemy AI count multiplier"
   Target_ko_kr "적 AI 수 배율"
   Modified 1620882710
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6155376BAE5CD00A}" {
   Id "COE-Editor_EnemyAISkill_Attribute_Description"
   Target_en_us "Set skill for enemy AI."
   Target_ko_kr "적 AI의 난이도를 설정합니다."
   Modified 1632976935
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6155376BB5461EDD}" {
   Id "COE-Editor_EnemyAISkill_Attribute_Name"
   Target_en_us "Enemy AI Skill"
   Target_ko_kr "적 AI 난이도"
   Modified 1632976926
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{65EB691767D4BEBC}" {
   Id "COE-Editor_EnemyArmoredVehicleCount_Attribute_Description"
   Target_en_us "Number of enemy armored vehicles to spawn for an AO"
   Target_ko_kr "작전구역마다 생성할 적 장갑차 수"
   Modified 1709932015
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{65EB691760944E2D}" {
   Id "COE-Editor_EnemyArmoredVehicleCount_Attribute_Name"
   Target_en_us "Enemy armored vehicle count"
   Target_ko_kr "적 장갑차 수"
   Modified 1709931992
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6098EB5536406790}" {
   Id "COE-Editor_EnemyFaction_Attribute_Description"
   Target_en_us "Set faction for enemy AI"
   Target_ko_kr "적 AI의 세력을 설정합니다"
   Modified 1620643576
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB55F24E9EDC}" {
   Id "COE-Editor_EnemyFaction_Attribute_Name"
   Target_en_us "Enemy faction"
   Target_ko_kr "적 세력"
   Modified 1620643419
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{65EF37288E0EE5A8}" {
   Id "COE-Editor_EnemyMortarCount_Attribute_Description"
   Target_en_us "Number of enemy mortars for support"
   Target_ko_kr "지원에 쓰일 적 박격포 수"
   Modified 1710180455
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{65EF372881BCE7EF}" {
   Id "COE-Editor_EnemyMortarCount_Attribute_Name"
   Target_en_us "Enemy mortar count"
   Target_ko_kr "적 박격포 수"
   Modified 1710180471
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{65EF3727E8B545D4}" {
   Id "COE-Editor_EnemySupportEnabled_Attribute_Description"
   Target_en_us "Whether enemy can support their AOs"
   Target_ko_kr "적이 자신의 작전구역을 지원할 수 있는지 여부"
   Modified 1710179976
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{65EF3727EE3C913A}" {
   Id "COE-Editor_EnemySupportEnabled_Attribute_Name"
   Target_en_us "Enemy Support"
   Target_ko_kr "적 지원"
   Modified 1710179938
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{65EF3728A02571A0}" {
   Id "COE-Editor_MaxEnemyReinforcementTime_Attribute_Description"
   Target_en_us "Maximum time in minutes required for the enemy to send reinforcements"
   Target_ko_kr "적이 지원병력을 보내는 데 걸리는 최대 시간(분)"
   Modified 1710180580
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{65EF3728D595124A}" {
   Id "COE-Editor_MaxEnemyReinforcementTime_Attribute_Name"
   Target_en_us "Max reinforcement time"
   Target_ko_kr "지원병력 최대 시간"
   Modified 1710180612
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{609C9CFFB03B11FC}" {
   Id "COE-Editor_MinEnemyAICount_Attribute_Description"
   Target_en_us "Minimum enemy AI count for an AO"
   Target_ko_kr "작전구역의 최소 적 AI 수"
   Modified 1620882697
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609C9CFFB4E1B11F}" {
   Id "COE-Editor_MinEnemyAICount_Attribute_Name"
   Target_en_us "Minimum enemy AI count"
   Target_ko_kr "최소 적 AI 수"
   Modified 1620882678
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{65EF3728AD02A735}" {
   Id "COE-Editor_MinEnemyReinforcementTime_Attribute_Description"
   Target_en_us "Minimum time in minutes required for the enemy to send reinforcements"
   Target_ko_kr "적이 지원병력을 보내는 데 걸리는 최소 시간(분)"
   Modified 1710180601
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{65EF3728AB7704FC}" {
   Id "COE-Editor_MinEnemyReinforcementTime_Attribute_Name"
   Target_en_us "Min reinforcement time"
   Target_ko_kr "지원병력 최소 시간"
   Modified 1710180603
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6098EB5564A954FF}" {
   Id "COE-Editor_NumRemObjectives_Attribute_Description"
   Target_en_us "Number of objectives before session ends"
   Target_ko_kr "세션이 끝나기 전까지 수행할 목표 수"
   Modified 1620643918
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB55634BE030}" {
   Id "COE-Editor_NumRemObjectives_Attribute_Name"
   Target_en_us "Number of remaining objectives"
   Target_ko_kr "남은 목표 수"
   Modified 1620643886
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB56F66BA92F}" {
   Id "COE-Editor_ObjectiveAttributes_Name"
   Target_en_us "Objective Properties"
   Target_ko_kr "목표 속성"
   Modified 1620644289
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB5535B86F8D}" {
   Id "COE-Editor_PlayerFaction_Attribute_Description"
   Target_en_us "Set the faction for the players. All already spawned players will get killed."
   Target_ko_kr "플레이어의 세력을 설정합니다. 이미 투입된 플레이어는 모두 사망합니다."
   Modified 1620643542
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB55E915DC64}" {
   Id "COE-Editor_PlayerFaction_Attribute_Name"
   Target_en_us "Player faction"
   Target_ko_kr "플레이어 세력"
   Modified 1620643413
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{61729194C3C2777F}" {
   Id "COE-FieldManual_Keybind_ShowScoreboard"
   Target_en_us "Show player list for nominating yourself as commander"
   Target_ko_kr "플레이어 목록을 열어 자신을 지휘관 후보로 추천"
   Modified 1634906936
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{6172918012D7BC0E}" {
   Id "COE-FieldManual_Page_Commander_Text_00"
   Target_en_us "Commander is a votable role that can change the scenario properties, set up missions and place insertion and exfil points."
   Target_ko_kr "지휘관은 투표로 선출되는 역할로, 시나리오 속성을 변경하고 임무를 설정하며 투입 지점과 탈출 지점을 배치할 수 있습니다."
   Modified 1727861908
   Author "Kex"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{61729182BBA06C85}" {
   Id "COE-FieldManual_Page_Commander_Text_01"
   Target_en_us "Commander Actions"
   Target_ko_kr "지휘관 액션"
   Modified 1727862134
   Author "Kex"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{61729182D079A9C9}" {
   Id "COE-FieldManual_Page_Commander_Text_02"
   Target_en_us "Commander can execute actions such as setting up tasks via the board or commanding menu."
   Target_ko_kr "지휘관은 상황판이나 지휘 메뉴를 통해 임무 설정 같은 액션을 실행할 수 있습니다."
   Modified 1727863725
   Author "Kex"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{617291820B539877}" {
   Id "COE-FieldManual_Page_Commander_Text_03"
   Target_en_us "1. Select AOs and tasks"
   Target_ko_kr "1. 작전구역 및 임무 선택"
   Modified 1727862536
   Author "Kex"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6172918201FA959E}" {
   Id "COE-FieldManual_Page_Commander_Text_04"
   Target_en_us "Commander can select tasks by opening the selection menu on the board or commanding menu. Then open the map context menu on a location icon to add tasks."
   Target_ko_kr "지휘관은 상황판이나 지휘 메뉴에서 선택 메뉴를 열어 임무를 선택할 수 있습니다. 그다음 장소 아이콘에서 지도 컨텍스트 메뉴를 열어 임무를 추가하세요."
   Modified 1727862509
   Author "Kex"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{66FD131FF9CA0521}" {
   Id "COE-FieldManual_Page_Commander_Text_05"
   Target_en_us "2. Set up insertion and exfil points"
   Target_ko_kr "2. 투입 지점 및 탈출 지점 설정"
   Modified 1727862531
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{66FD131FFF014623}" {
   Id "COE-FieldManual_Page_Commander_Text_06"
   Target_en_us "Commanders can set up insertion and exfil points via the map context menu, either inside the AO selection menu or on the regular map."
   Target_ko_kr "지휘관은 작전구역 선택 메뉴 안이나 일반 지도에서 지도 컨텍스트 메뉴를 통해 투입 지점과 탈출 지점을 설정할 수 있습니다."
   Modified 1727862600
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6172918F148C1106}" {
   Id "COE-KeybindMap_MapContextualMenu"
   Target_en_us "Map contextual menu"
   Target_ko_kr "지도 컨텍스트 메뉴"
   Modified 1634903843
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{60A0A467427CC45C}" {
   Id "COE-MapLocation_Safehouse"
   Target_en_us "Safehouse"
   Target_ko_kr "안전 가옥"
   Modified 1621145325
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4152E9566B}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_IN_FAIL"
   Target_en_us "Vote for %1 to become Commander failed"
   Target_ko_kr "%1님의 지휘관 선정 투표가 실패했습니다"
   Modified 1620637825
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB41548CB0FF}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_IN_START"
   Target_en_us "Start vote to become Commander"
   Target_ko_kr "지휘관 선정 투표 시작"
   Modified 1620637859
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB415254BD5B}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_IN_SUCCEED"
   Target_en_us "Vote to become Commander successful, %1 is now Commander"
   Target_ko_kr "지휘관 선정 투표가 성공했습니다, %1님은 이제 지휘관입니다"
   Modified 1620637824
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4153FEF1E2}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_IN_VOTE_ABSTAINED"
   Target_en_us "You abstained from voting for %1 becoming Commander"
   Target_ko_kr "%1님의 지휘관 선정 투표에서 기권했습니다"
   Modified 1620637826
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB41536D08CB}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_IN_VOTE_CASTED"
   Target_en_us "You voted in favor of %1 becoming Commander"
   Target_ko_kr "%1님의 지휘관 선정 투표에서 찬성표를 던졌습니다"
   Modified 1620637826
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4150C7A516}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_OUT_FAIL"
   Target_en_us "Vote to revoke Commander rights failed, %1 is still Commander"
   Target_ko_kr "지휘관 해임 투표가 실패했습니다, %1님은 아직 지휘관입니다"
   Modified 1620637828
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB415028FFE0}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_OUT_START"
   Target_en_us "Vote started to revoke Commander role from %1"
   Target_ko_kr "%1님의 지휘관 해임 투표가 시작되었습니다"
   Modified 1620641425
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB41509209FC}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_OUT_SUCCEED"
   Target_en_us "Vote to remove Commander successful, %1 is no longer Commander"
   Target_ko_kr "지휘관 해임 투표가 성공했습니다, %1님은 더 이상 지휘관이 아닙니다"
   Modified 1620637827
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB415172409B}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_OUT_VOTE_ABSTAINED"
   Target_en_us "You abstained from voting to revoke the Commander role for %1"
   Target_ko_kr "%1님의 지휘관 해임 투표에서 기권했습니다"
   Modified 1620641634
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4151014E77}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_OUT_VOTE_CASTED"
   Target_en_us "You voted in favor of revoking Commander role for %1"
   Target_ko_kr "%1님의 지휘관 해임 투표에서 찬성표를 던졌습니다"
   Modified 1620641607
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609AD01DEF816FDD}" {
   Id "COE-Notification_EDITOR_COMMANDER_RIGHTS_ASSIGNED"
   Target_en_us "%1 gained commander role"
   Target_ko_kr "%1님이 지휘관 역할을 맡았습니다"
   Modified 1620759693
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609AD01DE9C7414C}" {
   Id "COE-Notification_EDITOR_COMMANDER_RIGHTS_REMOVED"
   Target_en_us "%1 lost commander role"
   Target_ko_kr "%1님이 지휘관 역할을 잃었습니다"
   Modified 1620759702
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4A96030214}" {
   Id "COE-Notification_Sticky_VoteCommander"
   Target_en_us "Vote %1 to become Commander"
   Target_ko_kr "투표해서 %1님을 지휘관으로 선출하세요"
   Modified 1620641372
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4AAD21608E}" {
   Id "COE-Notification_Sticky_VoteRemove_Commander"
   Target_en_us "Vote %1 to revoke Commander role"
   Target_ko_kr "투표해서 %1님을 지휘관에서 해임하세요"
   Modified 1620641583
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609A2A3512083599}" {
   Id "COE-Reason_NoAOGenerated"
   Target_en_us "No AO Generated"
   Target_ko_kr "생성된 작전구역 없음"
   Modified 1727743061
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{66FB249D34DDF4F7}" {
   Id "COE-Reason_NoAOSelected"
   Target_en_us "No AO Selected"
   Target_ko_kr "선택된 작전구역 없음"
   Modified 1727743084
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{66FB2482B7F8AB77}" {
   Id "COE-Reason_NoExfilPoint"
   Target_en_us "No Exfil Point"
   Target_ko_kr "탈출 지점 없음"
   Modified 1727742403
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{612881F66CCCA0B3}" {
   Id "COE-Reason_NoInsertionPoint"
   Target_en_us "No Insertion Point"
   Target_ko_kr "투입 지점 없음"
   Modified 1630047446
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609A2A291B7DDB18}" {
   Id "COE-Reason_OngoingAO"
   Target_en_us "Ongoing AO"
   Target_ko_kr "작전구역 진행 중"
   Modified 1620739396
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609A2A3F4AC93B53}" {
   Id "COE-Reason_OngoingBriefing"
   Target_en_us "Ongoing briefing"
   Target_ko_kr "브리핑 진행 중"
   Modified 1620744312
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4A8D475C83}" {
   Id "COE-Voting_COMMANDER_IN_AbstainVotingName"
   Target_en_us "Abstain from voting for Commander"
   Target_ko_kr "지휘관 선정 투표에서 기권"
   Modified 1620641197
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4BED8B425B}" {
   Id "COE-Voting_COMMANDER_IN_AddVoteName"
   Target_en_us "Vote for Commander"
   Target_ko_kr "지휘관 투표"
   Modified 1620640875
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4A8680F9E6}" {
   Id "COE-Voting_COMMANDER_IN_CancelVotingName"
   Target_en_us "Cancel vote to become Commander"
   Target_ko_kr "지휘관 선정 투표 취소"
   Modified 1620641146
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4B6E4E7F35}" {
   Id "COE-Voting_COMMANDER_IN_StartVotingName"
   Target_en_us "Start vote to become Commander"
   Target_ko_kr "지휘관 선정 투표 시작"
   Modified 1620640899
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4AA3DF4665}" {
   Id "COE-Voting_COMMANDER_OUT_AbstainVotingName"
   Target_en_us "Abstain from voting for removing Commander"
   Target_ko_kr "지휘관 해임 투표에서 기권"
   Modified 1620641531
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4A999E0BF2}" {
   Id "COE-Voting_COMMANDER_OUT_CancelVotingName"
   Target_en_us "Cancel vote to remove Commander"
   Target_ko_kr "지휘관 해임 투표 취소"
   Modified 1620641171
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4A9C5C1B72}" {
   Id "COE-Voting_COMMANDER_OUT_StartVotingName"
   Target_en_us "Start vote to remove Commander"
   Target_ko_kr "지휘관 해임 투표 시작"
   Modified 1620641514
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4AB24C73EC}" {
   Id "COE-Voting_COMMANDER_WIDRAW_Name"
   Target_en_us "Relinquish Commander role"
   Target_ko_kr "지휘관 역할 포기"
   Modified 1620641067
   Author "kex"
   LastChanged "kex"
  }
 }
}