StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{609A2A3C9AC2C20F}" {
   Id "COE-Action_Briefing"
   Target_en_us "Enter briefing"
   Modified 1620744497
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609A2A3C8BABD4C6}" {
   Id "COE-Action_CancelAO"
   Target_en_us "Cancel AO"
   Modified 1620744428
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609F29E24795601A}" {
   Id "COE-Action_ConfirmCancelAO"
   Target_en_us "CONFIRM CANCEL AO"
   Modified 1621047048
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6099212B7E1B92EE}" {
   Id "COE-Action_GenerateAO"
   Target_en_us "Generate AO"
   Modified 1620742993
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB566634958C}" {
   Id "COE-Action_ObjectiveAttributes"
   Target_en_us "Open objective properties"
   Modified 1620743183
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609F29E23AC05072}" {
   Id "COE-Action_QuitCancelAO"
   Target_en_us "Quit cancel AO"
   Modified 1621047068
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB56B679A6E9}" {
   Id "COE-Action_SelectAO"
   Target_en_us "Select AO"
   Modified 1620742934
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{66FB2482928FE156}" {
   Id "COE-Action_SetExfilPoint"
   Target_en_us "Set exfil point"
   Target_de_de "S"
   Modified 1727742336
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{609F29E3E0663A77}" {
   Id "COE-Action_SetInsertionPoint"
   Target_en_us "Set insertion point"
   Modified 1621047339
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{60A0A47D302DACF1}" {
   Id "COE-ActionCategory_CombatOpsCommands"
   Target_en_us "Combat Ops Commands"
   Modified 1621412051
   Author "kex"
   LastChanged "swellig"
  }
  CustomStringTableItem "{6172533A32929855}" {
   Id "COE-Briefing_Description"
   Target_en_us "Co-operative infantry gameplay with dynamic objectives for Arma Reforger. Next generation of Combat Ops Enhanced with inspiration from mbrdmn's Dynamic Recon Ops from Arma 3."\
   ""
   Modified 1634888121
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{6155376789FAB1FC}" {
   Id "COE-DeployScreen_NoFactionsAvailable"
   Target_en_us "There are no available factions. Please vote for a commander or wait for them to set a faction."
   Modified 1632978970
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB52AA9BEC47}" {
   Id "COE-Dialog_SelectAO_Location"
   Target_en_us "Location:"
   Modified 1620743035
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{61585B1D0CD2464E}" {
   Id "COE-Editor_AORadius_Attribute_Description"
   Target_en_us "Set radius of the AO"
   Modified 1633217948
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{61585B1D03EC739D}" {
   Id "COE-Editor_AORadius_Attribute_Name"
   Target_en_us "AO radius"
   Modified 1633217920
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609C43226A8405AB}" {
   Id "COE-Editor_AttributeCategory_CombatOps_Name"
   Target_en_us "Combat Ops"
   Modified 1620867316
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6594C0799DBF5B9D}" {
   Id "COE-Editor_CivilianFaction_Attribute_Description"
   Target_en_us "Set faction for civilian AI"
   Modified 1704248386
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6594C0799BF012BF}" {
   Id "COE-Editor_CivilianFaction_Attribute_Name"
   Target_en_us "Civilian faction"
   Modified 1704248370
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{630708E9CB6A6A2D}" {
   Id "COE-Editor_CiviliansEnabled_Attribute_Description"
   Target_en_us "Set whether civilians should be spawned"
   Modified 1661407709
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{630708E9D59FD9AC}" {
   Id "COE-Editor_CiviliansEnabled_Attribute_Name"
   Target_en_us "Spawn civilians"
   Modified 1661407688
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6098EB54F6C1E4B8}" {
   Id "COE-Editor_CommanderMode_Name"
   Target_en_us "Commander"
   Modified 1620644120
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609C9CFFC2CE19E5}" {
   Id "COE-Editor_EnemyAICountMultiplier_Attribute_Description"
   Target_en_us "Total enemy AI count for an AO will be this multiplier times the total player count (ignored when below minimum count)"
   Modified 1620882763
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609C9CFFC6C3DF41}" {
   Id "COE-Editor_EnemyAICountMultiplier_Attribute_Name"
   Target_en_us "Enemy AI count multiplier"
   Modified 1620882710
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6155376BAE5CD00A}" {
   Id "COE-Editor_EnemyAISkill_Attribute_Description"
   Target_en_us "Set skill for enemy AI."
   Modified 1632976935
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6155376BB5461EDD}" {
   Id "COE-Editor_EnemyAISkill_Attribute_Name"
   Target_en_us "Enemy AI Skill"
   Modified 1632976926
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{65EB691767D4BEBC}" {
   Id "COE-Editor_EnemyArmoredVehicleCount_Attribute_Description"
   Target_en_us "Number of enemy armored vehicles to spawn for an AO"
   Modified 1709932015
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{65EB691760944E2D}" {
   Id "COE-Editor_EnemyArmoredVehicleCount_Attribute_Name"
   Target_en_us "Enemy armored vehicle count"
   Modified 1709931992
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6098EB5536406790}" {
   Id "COE-Editor_EnemyFaction_Attribute_Description"
   Target_en_us "Set faction for enemy AI"
   Modified 1620643576
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB55F24E9EDC}" {
   Id "COE-Editor_EnemyFaction_Attribute_Name"
   Target_en_us "Enemy faction"
   Modified 1620643419
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{65EF37288E0EE5A8}" {
   Id "COE-Editor_EnemyMortarCount_Attribute_Description"
   Target_en_us "Number of enemy mortars for support"
   Modified 1710180455
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{65EF372881BCE7EF}" {
   Id "COE-Editor_EnemyMortarCount_Attribute_Name"
   Target_en_us "Enemy mortar count"
   Modified 1710180471
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{65EF3727E8B545D4}" {
   Id "COE-Editor_EnemySupportEnabled_Attribute_Description"
   Target_en_us "Whether enemy can support their AOs"
   Modified 1710179976
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{65EF3727EE3C913A}" {
   Id "COE-Editor_EnemySupportEnabled_Attribute_Name"
   Target_en_us "Enemy Support"
   Modified 1710179938
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{65EF3728A02571A0}" {
   Id "COE-Editor_MaxEnemyReinforcementTime_Attribute_Description"
   Target_en_us "Maximum time in minutes required for the enemy to send reinforcements"
   Modified 1710180580
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{65EF3728D595124A}" {
   Id "COE-Editor_MaxEnemyReinforcementTime_Attribute_Name"
   Target_en_us "Max reinforcement time"
   Modified 1710180612
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{609C9CFFB03B11FC}" {
   Id "COE-Editor_MinEnemyAICount_Attribute_Description"
   Target_en_us "Minimum enemy AI count for an AO"
   Modified 1620882697
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609C9CFFB4E1B11F}" {
   Id "COE-Editor_MinEnemyAICount_Attribute_Name"
   Target_en_us "Minimum enemy AI count"
   Modified 1620882678
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{65EF3728AD02A735}" {
   Id "COE-Editor_MinEnemyReinforcementTime_Attribute_Description"
   Target_en_us "Minimum time in minutes required for the enemy to send reinforcements"
   Modified 1710180601
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{65EF3728AB7704FC}" {
   Id "COE-Editor_MinEnemyReinforcementTime_Attribute_Name"
   Target_en_us "Min reinforcement time"
   Modified 1710180603
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6098EB5564A954FF}" {
   Id "COE-Editor_NumRemObjectives_Attribute_Description"
   Target_en_us "Number of objectives before session ends"
   Modified 1620643918
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB55634BE030}" {
   Id "COE-Editor_NumRemObjectives_Attribute_Name"
   Target_en_us "Number of remaining objectives"
   Modified 1620643886
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB56F66BA92F}" {
   Id "COE-Editor_ObjectiveAttributes_Name"
   Target_en_us "Objective Properties"
   Modified 1620644289
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB5535B86F8D}" {
   Id "COE-Editor_PlayerFaction_Attribute_Description"
   Target_en_us "Set the faction for the players. All already spawned players will get killed."
   Modified 1620643542
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB55E915DC64}" {
   Id "COE-Editor_PlayerFaction_Attribute_Name"
   Target_en_us "Player faction"
   Modified 1620643413
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{61729194C3C2777F}" {
   Id "COE-FieldManual_Keybind_ShowScoreboard"
   Target_en_us "Show player list for nominating yourself as commander"
   Modified 1634906936
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{6172918012D7BC0E}" {
   Id "COE-FieldManual_Page_Commander_Text_00"
   Target_en_us "Commander is a votable role that can change the scenario properties, set up missions and place insertion points."
   Modified 1634901572
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{61729182BBA06C85}" {
   Id "COE-FieldManual_Page_Commander_Text_01"
   Target_en_us "1. Set up AO"
   Modified 1634906330
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{61729182D079A9C9}" {
   Id "COE-FieldManual_Page_Commander_Text_02"
   Target_en_us "Commanders can change the scenario properties, select the location and tasks and generate the AO via the board or commanding menu."
   Modified 1634904088
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{617291820B539877}" {
   Id "COE-FieldManual_Page_Commander_Text_03"
   Target_en_us "2. Set up insertion point"
   Modified 1634906267
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{6172918201FA959E}" {
   Id "COE-FieldManual_Page_Commander_Text_04"
   Target_en_us "Commanders can set up an insertion point via the map commanding menu once an AO has been generated."
   Modified 1634906153
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{6172918F148C1106}" {
   Id "COE-KeybindMap_MapContextualMenu"
   Target_en_us "Map contextual menu"
   Modified 1634903843
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{60A0A467427CC45C}" {
   Id "COE-MapLocation_Safehouse"
   Target_en_us "Safehouse"
   Modified 1621145325
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4152E9566B}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_IN_FAIL"
   Target_en_us "Vote for %1 to become Commander failed"
   Modified 1620637825
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB41548CB0FF}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_IN_START"
   Target_en_us "Start vote to become Commander"
   Modified 1620637859
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB415254BD5B}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_IN_SUCCEED"
   Target_en_us "Vote to become Commander successful, %1 is now Commander"
   Modified 1620637824
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4153FEF1E2}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_IN_VOTE_ABSTAINED"
   Target_en_us "You abstained from voting for %1 becoming Commander"
   Modified 1620637826
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB41536D08CB}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_IN_VOTE_CASTED"
   Target_en_us "You voted in favor of %1 becoming Commander"
   Modified 1620637826
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4150C7A516}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_OUT_FAIL"
   Target_en_us "Vote to revoke Commander rights failed, %1 is still Commander"
   Modified 1620637828
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB415028FFE0}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_OUT_START"
   Target_en_us "Vote started to revoke Commander role from %1"
   Modified 1620641425
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB41509209FC}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_OUT_SUCCEED"
   Target_en_us "Vote to remove Commander successful, %1 is no longer Commander"
   Modified 1620637827
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB415172409B}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_OUT_VOTE_ABSTAINED"
   Target_en_us "You abstained from voting to revoke the Commander role for %1"
   Modified 1620641634
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4151014E77}" {
   Id "COE-Notification_COE_VOTING_COMMANDER_OUT_VOTE_CASTED"
   Target_en_us "You voted in favor of revoking Commander role for %1"
   Modified 1620641607
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609AD01DEF816FDD}" {
   Id "COE-Notification_EDITOR_COMMANDER_RIGHTS_ASSIGNED"
   Target_en_us "%1 gained commander role"
   Modified 1620759693
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609AD01DE9C7414C}" {
   Id "COE-Notification_EDITOR_COMMANDER_RIGHTS_REMOVED"
   Target_en_us "%1 lost commander role"
   Modified 1620759702
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4A96030214}" {
   Id "COE-Notification_Sticky_VoteCommander"
   Target_en_us "Vote %1 to become Commander"
   Modified 1620641372
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4AAD21608E}" {
   Id "COE-Notification_Sticky_VoteRemove_Commander"
   Target_en_us "Vote %1 to revoke Commander role"
   Modified 1620641583
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609A2A3512083599}" {
   Id "COE-Reason_NoAOGenerated"
   Target_en_us "No AO Generated"
   Modified 1727743061
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{66FB249D34DDF4F7}" {
   Id "COE-Reason_NoAOSelected"
   Target_en_us "No AO Selected"
   Modified 1727743084
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{66FB2482B7F8AB77}" {
   Id "COE-Reason_NoExfilPoint"
   Target_en_us "No Exfil Point"
   Modified 1727742403
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{612881F66CCCA0B3}" {
   Id "COE-Reason_NoInsertionPoint"
   Target_en_us "No Insertion Point"
   Modified 1630047446
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609A2A291B7DDB18}" {
   Id "COE-Reason_OngoingAO"
   Target_en_us "Ongoing AO"
   Modified 1620739396
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{609A2A3F4AC93B53}" {
   Id "COE-Reason_OngoingBriefing"
   Target_en_us "Ongoing briefing"
   Modified 1620744312
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4A8D475C83}" {
   Id "COE-Voting_COMMANDER_IN_AbstainVotingName"
   Target_en_us "Abstain from voting for Commander"
   Modified 1620641197
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4BED8B425B}" {
   Id "COE-Voting_COMMANDER_IN_AddVoteName"
   Target_en_us "Vote for Commander"
   Modified 1620640875
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4A8680F9E6}" {
   Id "COE-Voting_COMMANDER_IN_CancelVotingName"
   Target_en_us "Cancel vote to become Commander"
   Modified 1620641146
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4B6E4E7F35}" {
   Id "COE-Voting_COMMANDER_IN_StartVotingName"
   Target_en_us "Start vote to become Commander"
   Modified 1620640899
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4AA3DF4665}" {
   Id "COE-Voting_COMMANDER_OUT_AbstainVotingName"
   Target_en_us "Abstain from voting for removing Commander"
   Modified 1620641531
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4A999E0BF2}" {
   Id "COE-Voting_COMMANDER_OUT_CancelVotingName"
   Target_en_us "Cancel vote to remove Commander"
   Modified 1620641171
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4A9C5C1B72}" {
   Id "COE-Voting_COMMANDER_OUT_StartVotingName"
   Target_en_us "Start vote to remove Commander"
   Modified 1620641514
   Author "kex"
   LastChanged "kex"
  }
  CustomStringTableItem "{6098EB4AB24C73EC}" {
   Id "COE-Voting_COMMANDER_WIDRAW_Name"
   Target_en_us "Relinquish Commander role"
   Modified 1620641067
   Author "kex"
   LastChanged "kex"
  }
 }
}